package cn.no7player.mapper;

import cn.no7player.model.HongYin;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HongYinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongyin
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongyin
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    int insert(HongYin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongyin
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    int insertSelective(HongYin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongyin
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    HongYin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongyin
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    int updateByPrimaryKeySelective(HongYin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hongyin
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    int updateByPrimaryKey(HongYin record);

    /**
     * 根据相关条件查询
     * */
    List<HongYin> findSelective(@Param("xing") String xing, @Param("ming") String ming,
                                @Param("sex") String sex, @Param("birthday") String birthday);

    /**
     * 根据订单号查询
     * */
    HongYin findByOrderSignId(@Param("orderSignId") int orderSignIdId);

}