package cn.no7player.mapper;

import cn.no7player.model.OrderSign;

public interface OrderSignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    int insert(OrderSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    int insertSelective(OrderSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    OrderSign selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    int updateByPrimaryKeySelective(OrderSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    int updateByPrimaryKey(OrderSign record);

}