package cn.no7player.model;

import java.util.Date;

public class Afortune {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.Id
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.name
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.FIRT_NAME
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String FIRT_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.LAST_NAME
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String LAST_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.BIRTH
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String BIRTH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.NONGLI_YEAR
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String NONGLI_YEAR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.NONGLI_MONTH
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String NONGLI_MONTH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.NONGLI_DAY
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String NONGLI_DAY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.NONGLI_HOUR
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String NONGLI_HOUR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.ANIMAL
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String ANIMAL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.GENDER
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String GENDER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_NAME
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_ID
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_TYPE
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_TITLE
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_TITLE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_POEM
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_POEM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_INTRO
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_INTRO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_ENTITY_SIGN_CAREER
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_ENTITY_SIGN_CAREER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_ENTITY_SIGN_FAMILY
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_ENTITY_SIGN_FAMILY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_ENTITY_SIGN_EMOTION
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_ENTITY_SIGN_EMOTION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_ENTITY_SIGN_ACADEMIC
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_ENTITY_SIGN_ACADEMIC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_ENTITY_SIGN_INVEST
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_ENTITY_SIGN_INVEST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_ENTITY_SIGN_HEALTH
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_ENTITY_SIGN_HEALTH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_ENTITY_SIGN_SWITCH
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_ENTITY_SIGN_SWITCH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_ENTITY_SIGN_LAWSUIT
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_ENTITY_SIGN_LAWSUIT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_ENTITY_SIGN_LOST
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_ENTITY_SIGN_LOST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_ENTITY_SIGN_TRAVEL
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_ENTITY_SIGN_TRAVEL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.SIGN_ENTITY_SIGN_CHILD
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    private String SIGN_ENTITY_SIGN_CHILD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ifortune.create_time
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    private Date create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.Id
     *
     * @return the value of ifortune.Id
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.Id
     *
     * @param id the value for ifortune.Id
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.name
     *
     * @return the value of ifortune.name
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.name
     *
     * @param name the value for ifortune.name
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.FIRT_NAME
     *
     * @return the value of ifortune.FIRT_NAME
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getFIRT_NAME() {
        return FIRT_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.FIRT_NAME
     *
     * @param FIRT_NAME the value for ifortune.FIRT_NAME
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setFIRT_NAME(String FIRT_NAME) {
        this.FIRT_NAME = FIRT_NAME == null ? null : FIRT_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.LAST_NAME
     *
     * @return the value of ifortune.LAST_NAME
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getLAST_NAME() {
        return LAST_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.LAST_NAME
     *
     * @param LAST_NAME the value for ifortune.LAST_NAME
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setLAST_NAME(String LAST_NAME) {
        this.LAST_NAME = LAST_NAME == null ? null : LAST_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.BIRTH
     *
     * @return the value of ifortune.BIRTH
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getBIRTH() {
        return BIRTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.BIRTH
     *
     * @param BIRTH the value for ifortune.BIRTH
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setBIRTH(String BIRTH) {
        this.BIRTH = BIRTH == null ? null : BIRTH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.NONGLI_YEAR
     *
     * @return the value of ifortune.NONGLI_YEAR
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getNONGLI_YEAR() {
        return NONGLI_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.NONGLI_YEAR
     *
     * @param NONGLI_YEAR the value for ifortune.NONGLI_YEAR
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setNONGLI_YEAR(String NONGLI_YEAR) {
        this.NONGLI_YEAR = NONGLI_YEAR == null ? null : NONGLI_YEAR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.NONGLI_MONTH
     *
     * @return the value of ifortune.NONGLI_MONTH
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getNONGLI_MONTH() {
        return NONGLI_MONTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.NONGLI_MONTH
     *
     * @param NONGLI_MONTH the value for ifortune.NONGLI_MONTH
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setNONGLI_MONTH(String NONGLI_MONTH) {
        this.NONGLI_MONTH = NONGLI_MONTH == null ? null : NONGLI_MONTH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.NONGLI_DAY
     *
     * @return the value of ifortune.NONGLI_DAY
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getNONGLI_DAY() {
        return NONGLI_DAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.NONGLI_DAY
     *
     * @param NONGLI_DAY the value for ifortune.NONGLI_DAY
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setNONGLI_DAY(String NONGLI_DAY) {
        this.NONGLI_DAY = NONGLI_DAY == null ? null : NONGLI_DAY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.NONGLI_HOUR
     *
     * @return the value of ifortune.NONGLI_HOUR
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getNONGLI_HOUR() {
        return NONGLI_HOUR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.NONGLI_HOUR
     *
     * @param NONGLI_HOUR the value for ifortune.NONGLI_HOUR
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setNONGLI_HOUR(String NONGLI_HOUR) {
        this.NONGLI_HOUR = NONGLI_HOUR == null ? null : NONGLI_HOUR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.ANIMAL
     *
     * @return the value of ifortune.ANIMAL
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getANIMAL() {
        return ANIMAL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.ANIMAL
     *
     * @param ANIMAL the value for ifortune.ANIMAL
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setANIMAL(String ANIMAL) {
        this.ANIMAL = ANIMAL == null ? null : ANIMAL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.GENDER
     *
     * @return the value of ifortune.GENDER
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getGENDER() {
        return GENDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.GENDER
     *
     * @param GENDER the value for ifortune.GENDER
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setGENDER(String GENDER) {
        this.GENDER = GENDER == null ? null : GENDER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_NAME
     *
     * @return the value of ifortune.SIGN_NAME
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_NAME() {
        return SIGN_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_NAME
     *
     * @param SIGN_NAME the value for ifortune.SIGN_NAME
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_NAME(String SIGN_NAME) {
        this.SIGN_NAME = SIGN_NAME == null ? null : SIGN_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_ID
     *
     * @return the value of ifortune.SIGN_ID
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_ID() {
        return SIGN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_ID
     *
     * @param SIGN_ID the value for ifortune.SIGN_ID
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_ID(String SIGN_ID) {
        this.SIGN_ID = SIGN_ID == null ? null : SIGN_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_TYPE
     *
     * @return the value of ifortune.SIGN_TYPE
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_TYPE() {
        return SIGN_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_TYPE
     *
     * @param SIGN_TYPE the value for ifortune.SIGN_TYPE
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_TYPE(String SIGN_TYPE) {
        this.SIGN_TYPE = SIGN_TYPE == null ? null : SIGN_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_TITLE
     *
     * @return the value of ifortune.SIGN_TITLE
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_TITLE() {
        return SIGN_TITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_TITLE
     *
     * @param SIGN_TITLE the value for ifortune.SIGN_TITLE
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_TITLE(String SIGN_TITLE) {
        this.SIGN_TITLE = SIGN_TITLE == null ? null : SIGN_TITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_POEM
     *
     * @return the value of ifortune.SIGN_POEM
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_POEM() {
        return SIGN_POEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_POEM
     *
     * @param SIGN_POEM the value for ifortune.SIGN_POEM
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_POEM(String SIGN_POEM) {
        this.SIGN_POEM = SIGN_POEM == null ? null : SIGN_POEM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_INTRO
     *
     * @return the value of ifortune.SIGN_INTRO
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_INTRO() {
        return SIGN_INTRO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_INTRO
     *
     * @param SIGN_INTRO the value for ifortune.SIGN_INTRO
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_INTRO(String SIGN_INTRO) {
        this.SIGN_INTRO = SIGN_INTRO == null ? null : SIGN_INTRO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_ENTITY_SIGN_CAREER
     *
     * @return the value of ifortune.SIGN_ENTITY_SIGN_CAREER
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_ENTITY_SIGN_CAREER() {
        return SIGN_ENTITY_SIGN_CAREER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_ENTITY_SIGN_CAREER
     *
     * @param SIGN_ENTITY_SIGN_CAREER the value for ifortune.SIGN_ENTITY_SIGN_CAREER
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_ENTITY_SIGN_CAREER(String SIGN_ENTITY_SIGN_CAREER) {
        this.SIGN_ENTITY_SIGN_CAREER = SIGN_ENTITY_SIGN_CAREER == null ? null : SIGN_ENTITY_SIGN_CAREER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_ENTITY_SIGN_FAMILY
     *
     * @return the value of ifortune.SIGN_ENTITY_SIGN_FAMILY
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_ENTITY_SIGN_FAMILY() {
        return SIGN_ENTITY_SIGN_FAMILY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_ENTITY_SIGN_FAMILY
     *
     * @param SIGN_ENTITY_SIGN_FAMILY the value for ifortune.SIGN_ENTITY_SIGN_FAMILY
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_ENTITY_SIGN_FAMILY(String SIGN_ENTITY_SIGN_FAMILY) {
        this.SIGN_ENTITY_SIGN_FAMILY = SIGN_ENTITY_SIGN_FAMILY == null ? null : SIGN_ENTITY_SIGN_FAMILY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_ENTITY_SIGN_EMOTION
     *
     * @return the value of ifortune.SIGN_ENTITY_SIGN_EMOTION
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_ENTITY_SIGN_EMOTION() {
        return SIGN_ENTITY_SIGN_EMOTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_ENTITY_SIGN_EMOTION
     *
     * @param SIGN_ENTITY_SIGN_EMOTION the value for ifortune.SIGN_ENTITY_SIGN_EMOTION
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_ENTITY_SIGN_EMOTION(String SIGN_ENTITY_SIGN_EMOTION) {
        this.SIGN_ENTITY_SIGN_EMOTION = SIGN_ENTITY_SIGN_EMOTION == null ? null : SIGN_ENTITY_SIGN_EMOTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_ENTITY_SIGN_ACADEMIC
     *
     * @return the value of ifortune.SIGN_ENTITY_SIGN_ACADEMIC
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_ENTITY_SIGN_ACADEMIC() {
        return SIGN_ENTITY_SIGN_ACADEMIC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_ENTITY_SIGN_ACADEMIC
     *
     * @param SIGN_ENTITY_SIGN_ACADEMIC the value for ifortune.SIGN_ENTITY_SIGN_ACADEMIC
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_ENTITY_SIGN_ACADEMIC(String SIGN_ENTITY_SIGN_ACADEMIC) {
        this.SIGN_ENTITY_SIGN_ACADEMIC = SIGN_ENTITY_SIGN_ACADEMIC == null ? null : SIGN_ENTITY_SIGN_ACADEMIC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_ENTITY_SIGN_INVEST
     *
     * @return the value of ifortune.SIGN_ENTITY_SIGN_INVEST
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_ENTITY_SIGN_INVEST() {
        return SIGN_ENTITY_SIGN_INVEST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_ENTITY_SIGN_INVEST
     *
     * @param SIGN_ENTITY_SIGN_INVEST the value for ifortune.SIGN_ENTITY_SIGN_INVEST
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_ENTITY_SIGN_INVEST(String SIGN_ENTITY_SIGN_INVEST) {
        this.SIGN_ENTITY_SIGN_INVEST = SIGN_ENTITY_SIGN_INVEST == null ? null : SIGN_ENTITY_SIGN_INVEST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_ENTITY_SIGN_HEALTH
     *
     * @return the value of ifortune.SIGN_ENTITY_SIGN_HEALTH
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_ENTITY_SIGN_HEALTH() {
        return SIGN_ENTITY_SIGN_HEALTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_ENTITY_SIGN_HEALTH
     *
     * @param SIGN_ENTITY_SIGN_HEALTH the value for ifortune.SIGN_ENTITY_SIGN_HEALTH
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_ENTITY_SIGN_HEALTH(String SIGN_ENTITY_SIGN_HEALTH) {
        this.SIGN_ENTITY_SIGN_HEALTH = SIGN_ENTITY_SIGN_HEALTH == null ? null : SIGN_ENTITY_SIGN_HEALTH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_ENTITY_SIGN_SWITCH
     *
     * @return the value of ifortune.SIGN_ENTITY_SIGN_SWITCH
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_ENTITY_SIGN_SWITCH() {
        return SIGN_ENTITY_SIGN_SWITCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_ENTITY_SIGN_SWITCH
     *
     * @param SIGN_ENTITY_SIGN_SWITCH the value for ifortune.SIGN_ENTITY_SIGN_SWITCH
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_ENTITY_SIGN_SWITCH(String SIGN_ENTITY_SIGN_SWITCH) {
        this.SIGN_ENTITY_SIGN_SWITCH = SIGN_ENTITY_SIGN_SWITCH == null ? null : SIGN_ENTITY_SIGN_SWITCH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_ENTITY_SIGN_LAWSUIT
     *
     * @return the value of ifortune.SIGN_ENTITY_SIGN_LAWSUIT
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_ENTITY_SIGN_LAWSUIT() {
        return SIGN_ENTITY_SIGN_LAWSUIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_ENTITY_SIGN_LAWSUIT
     *
     * @param SIGN_ENTITY_SIGN_LAWSUIT the value for ifortune.SIGN_ENTITY_SIGN_LAWSUIT
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_ENTITY_SIGN_LAWSUIT(String SIGN_ENTITY_SIGN_LAWSUIT) {
        this.SIGN_ENTITY_SIGN_LAWSUIT = SIGN_ENTITY_SIGN_LAWSUIT == null ? null : SIGN_ENTITY_SIGN_LAWSUIT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_ENTITY_SIGN_LOST
     *
     * @return the value of ifortune.SIGN_ENTITY_SIGN_LOST
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_ENTITY_SIGN_LOST() {
        return SIGN_ENTITY_SIGN_LOST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_ENTITY_SIGN_LOST
     *
     * @param SIGN_ENTITY_SIGN_LOST the value for ifortune.SIGN_ENTITY_SIGN_LOST
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_ENTITY_SIGN_LOST(String SIGN_ENTITY_SIGN_LOST) {
        this.SIGN_ENTITY_SIGN_LOST = SIGN_ENTITY_SIGN_LOST == null ? null : SIGN_ENTITY_SIGN_LOST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_ENTITY_SIGN_TRAVEL
     *
     * @return the value of ifortune.SIGN_ENTITY_SIGN_TRAVEL
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_ENTITY_SIGN_TRAVEL() {
        return SIGN_ENTITY_SIGN_TRAVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_ENTITY_SIGN_TRAVEL
     *
     * @param SIGN_ENTITY_SIGN_TRAVEL the value for ifortune.SIGN_ENTITY_SIGN_TRAVEL
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_ENTITY_SIGN_TRAVEL(String SIGN_ENTITY_SIGN_TRAVEL) {
        this.SIGN_ENTITY_SIGN_TRAVEL = SIGN_ENTITY_SIGN_TRAVEL == null ? null : SIGN_ENTITY_SIGN_TRAVEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.SIGN_ENTITY_SIGN_CHILD
     *
     * @return the value of ifortune.SIGN_ENTITY_SIGN_CHILD
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public String getSIGN_ENTITY_SIGN_CHILD() {
        return SIGN_ENTITY_SIGN_CHILD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.SIGN_ENTITY_SIGN_CHILD
     *
     * @param SIGN_ENTITY_SIGN_CHILD the value for ifortune.SIGN_ENTITY_SIGN_CHILD
     *
     * @mbggenerated Sun Apr 07 15:10:20 CST 2019
     */
    public void setSIGN_ENTITY_SIGN_CHILD(String SIGN_ENTITY_SIGN_CHILD) {
        this.SIGN_ENTITY_SIGN_CHILD = SIGN_ENTITY_SIGN_CHILD == null ? null : SIGN_ENTITY_SIGN_CHILD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ifortune.create_time
     *
     * @return the value of ifortune.create_time
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ifortune.create_time
     *
     * @param create_time the value for ifortune.create_time
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }
}