package cn.no7player.model;

import java.util.Date;

public class HongYin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.Id
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.birthday
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.hour
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String hour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.minute
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String minute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.xing
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String xing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.ming
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String ming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.sex
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.xings
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String xings;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.mings
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String mings;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.shengyun
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String shengyun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.tiange
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String tiange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.renge
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String renge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.dige
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String dige;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.waige
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String waige;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.zongge
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String zongge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.zonglun
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String zonglun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.pingfen
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    private String pingfen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.jichuyun
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    private String jichuyun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.chenggongyun
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    private String chenggongyun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.shejiaoyun
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    private String shejiaoyun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hongyin.create_time
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    private Date create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.Id
     *
     * @return the value of hongyin.Id
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.Id
     *
     * @param id the value for hongyin.Id
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.birthday
     *
     * @return the value of hongyin.birthday
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.birthday
     *
     * @param birthday the value for hongyin.birthday
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.hour
     *
     * @return the value of hongyin.hour
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.hour
     *
     * @param hour the value for hongyin.hour
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setHour(String hour) {
        this.hour = hour == null ? null : hour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.minute
     *
     * @return the value of hongyin.minute
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getMinute() {
        return minute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.minute
     *
     * @param minute the value for hongyin.minute
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setMinute(String minute) {
        this.minute = minute == null ? null : minute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.xing
     *
     * @return the value of hongyin.xing
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getXing() {
        return xing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.xing
     *
     * @param xing the value for hongyin.xing
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setXing(String xing) {
        this.xing = xing == null ? null : xing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.ming
     *
     * @return the value of hongyin.ming
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getMing() {
        return ming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.ming
     *
     * @param ming the value for hongyin.ming
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setMing(String ming) {
        this.ming = ming == null ? null : ming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.sex
     *
     * @return the value of hongyin.sex
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.sex
     *
     * @param sex the value for hongyin.sex
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.xings
     *
     * @return the value of hongyin.xings
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getXings() {
        return xings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.xings
     *
     * @param xings the value for hongyin.xings
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setXings(String xings) {
        this.xings = xings == null ? null : xings.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.mings
     *
     * @return the value of hongyin.mings
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getMings() {
        return mings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.mings
     *
     * @param mings the value for hongyin.mings
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setMings(String mings) {
        this.mings = mings == null ? null : mings.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.shengyun
     *
     * @return the value of hongyin.shengyun
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getShengyun() {
        return shengyun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.shengyun
     *
     * @param shengyun the value for hongyin.shengyun
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setShengyun(String shengyun) {
        this.shengyun = shengyun == null ? null : shengyun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.tiange
     *
     * @return the value of hongyin.tiange
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getTiange() {
        return tiange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.tiange
     *
     * @param tiange the value for hongyin.tiange
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setTiange(String tiange) {
        this.tiange = tiange == null ? null : tiange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.renge
     *
     * @return the value of hongyin.renge
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getRenge() {
        return renge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.renge
     *
     * @param renge the value for hongyin.renge
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setRenge(String renge) {
        this.renge = renge == null ? null : renge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.dige
     *
     * @return the value of hongyin.dige
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getDige() {
        return dige;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.dige
     *
     * @param dige the value for hongyin.dige
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setDige(String dige) {
        this.dige = dige == null ? null : dige.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.waige
     *
     * @return the value of hongyin.waige
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getWaige() {
        return waige;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.waige
     *
     * @param waige the value for hongyin.waige
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setWaige(String waige) {
        this.waige = waige == null ? null : waige.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.zongge
     *
     * @return the value of hongyin.zongge
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getZongge() {
        return zongge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.zongge
     *
     * @param zongge the value for hongyin.zongge
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setZongge(String zongge) {
        this.zongge = zongge == null ? null : zongge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.zonglun
     *
     * @return the value of hongyin.zonglun
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getZonglun() {
        return zonglun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.zonglun
     *
     * @param zonglun the value for hongyin.zonglun
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public void setZonglun(String zonglun) {
        this.zonglun = zonglun == null ? null : zonglun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.pingfen
     *
     * @return the value of hongyin.pingfen
     *
     * @mbg.generated Thu May 02 14:50:22 CST 2019
     */
    public String getPingfen() {
        return pingfen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.pingfen
     *
     * @param pingfen the value for hongyin.pingfen
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    public void setPingfen(String pingfen) {
        this.pingfen = pingfen == null ? null : pingfen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.jichuyun
     *
     * @return the value of hongyin.jichuyun
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    public String getJichuyun() {
        return jichuyun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.jichuyun
     *
     * @param jichuyun the value for hongyin.jichuyun
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    public void setJichuyun(String jichuyun) {
        this.jichuyun = jichuyun == null ? null : jichuyun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.chenggongyun
     *
     * @return the value of hongyin.chenggongyun
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    public String getChenggongyun() {
        return chenggongyun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.chenggongyun
     *
     * @param chenggongyun the value for hongyin.chenggongyun
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    public void setChenggongyun(String chenggongyun) {
        this.chenggongyun = chenggongyun == null ? null : chenggongyun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.shejiaoyun
     *
     * @return the value of hongyin.shejiaoyun
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    public String getShejiaoyun() {
        return shejiaoyun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.shejiaoyun
     *
     * @param shejiaoyun the value for hongyin.shejiaoyun
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    public void setShejiaoyun(String shejiaoyun) {
        this.shejiaoyun = shejiaoyun == null ? null : shejiaoyun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hongyin.create_time
     *
     * @return the value of hongyin.create_time
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hongyin.create_time
     *
     * @param create_time the value for hongyin.create_time
     *
     * @mbg.generated Thu May 02 14:50:23 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }
}