package cn.no7player.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrderSign {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_sign.Id
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_sign.order_id
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    private String order_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_sign.transaction_id
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    private String transaction_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_sign.ifortune_id
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    private Integer ifortune_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_sign.amount
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_sign.create_time
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_sign.del_flag
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    private Integer del_flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_sign.pay_type
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    private String pay_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_sign.channel
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    private String channel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_sign.Id
     *
     * @return the value of order_sign.Id
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_sign.Id
     *
     * @param id the value for order_sign.Id
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_sign.order_id
     *
     * @return the value of order_sign.order_id
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_sign.order_id
     *
     * @param order_id the value for order_sign.order_id
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_sign.transaction_id
     *
     * @return the value of order_sign.transaction_id
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_sign.transaction_id
     *
     * @param transaction_id the value for order_sign.transaction_id
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_sign.ifortune_id
     *
     * @return the value of order_sign.ifortune_id
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public Integer getIfortune_id() {
        return ifortune_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_sign.ifortune_id
     *
     * @param ifortune_id the value for order_sign.ifortune_id
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public void setIfortune_id(Integer ifortune_id) {
        this.ifortune_id = ifortune_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_sign.amount
     *
     * @return the value of order_sign.amount
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_sign.amount
     *
     * @param amount the value for order_sign.amount
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_sign.create_time
     *
     * @return the value of order_sign.create_time
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_sign.create_time
     *
     * @param create_time the value for order_sign.create_time
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_sign.del_flag
     *
     * @return the value of order_sign.del_flag
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public Integer getDel_flag() {
        return del_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_sign.del_flag
     *
     * @param del_flag the value for order_sign.del_flag
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public void setDel_flag(Integer del_flag) {
        this.del_flag = del_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_sign.pay_type
     *
     * @return the value of order_sign.pay_type
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public String getPay_type() {
        return pay_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_sign.pay_type
     *
     * @param pay_type the value for order_sign.pay_type
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public void setPay_type(String pay_type) {
        this.pay_type = pay_type == null ? null : pay_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_sign.channel
     *
     * @return the value of order_sign.channel
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_sign.channel
     *
     * @param channel the value for order_sign.channel
     *
     * @mbg.generated Sun May 05 10:08:57 CST 2019
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }
}