package cn.no7player.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrderSign {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.Id
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    private String order_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_sign.transaction_id
     *
     * @mbg.generated Sun Apr 28 09:24:27 CST 2019
     */
    private String transaction_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ifortune_id
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    private Integer ifortune_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.amount
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.del_flag
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    private Integer del_flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.Id
     *
     * @return the value of order.Id
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.Id
     *
     * @param id the value for order.Id
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param order_id the value for order.order_id
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id == null ? null : order_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_sign.transaction_id
     *
     * @return the value of order_sign.transaction_id
     *
     * @mbg.generated Sun Apr 28 09:24:27 CST 2019
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_sign.transaction_id
     *
     * @param transaction_id the value for order_sign.transaction_id
     *
     * @mbg.generated Sun Apr 28 09:24:27 CST 2019
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ifortune_id
     *
     * @return the value of order.ifortune_id
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    public Integer getIfortune_id() {
        return ifortune_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ifortune_id
     *
     * @param ifortune_id the value for order.ifortune_id
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    public void setIfortune_id(Integer ifortune_id) {
        this.ifortune_id = ifortune_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.amount
     *
     * @return the value of order.amount
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.amount
     *
     * @param amount the value for order.amount
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param create_time the value for order.create_time
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.del_flag
     *
     * @return the value of order.del_flag
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    public Integer getDel_flag() {
        return del_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.del_flag
     *
     * @param del_flag the value for order.del_flag
     *
     * @mbg.generated Thu Apr 11 09:32:55 CST 2019
     */
    public void setDel_flag(Integer del_flag) {
        this.del_flag = del_flag;
    }
}